# Generated by Django 3.0.2 on 2020-01-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_contact_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='type',
            new_name='value',
        ),
    ]
