# Generated by Django 3.0.2 on 2020-01-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20200126_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_by_choices',
            field=models.CharField(choices=[(1, 'PHONE'), (2, 'FACEBOOK'), (3, 'EMAIL')], default=1, max_length=10),
        ),
    ]
