# Generated by Django 3.0.2 on 2020-02-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20200126_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branches',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contacts',
            new_name='course',
        ),
    ]
